version: '3'

services:
  api:
    build:
      context: ./
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_DATABASE: aquinasnetwork
      MYSQL_USER: guille1999
      MYSQL_PASSWORD: prueba-tecnica
      MYSQL_PORT: 3306
    command: ["./wait-for-mysql.sh", "mysql", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: prueba-tecnica
      MYSQL_DATABASE: aquinasnetwork
      MYSQL_USER: guille1999
      MYSQL_PASSWORD: prueba-tecnica
    ports:
      - "3306:3306"